Allow passing alternative architecture for assets download

diff --git a/scripts/get-fedora-coreos b/scripts/get-fedora-coreos
--- a/scripts/get-fedora-coreos
+++ b/scripts/get-fedora-coreos
@@ -1,18 +1,19 @@
 #!/usr/bin/env bash
 # USAGE: ./scripts/get-fedora-coreos
-# USAGE: ./scripts/get-fedora-coreos stream version dest
+# USAGE: ./scripts/get-fedora-coreos stream version dest arch
 #
 set -eou pipefail
 
 STREAM=${1:-"stable"}
 VERSION=${2:-"33.20210117.3.2"}
 DEST_DIR=${3:-"$PWD/examples/assets"}
-DEST=$DEST_DIR/fedora-coreos
-BASE_URL=https://builds.coreos.fedoraproject.org/prod/streams/$STREAM/builds/$VERSION/x86_64
+ARCH=${4:-"x86_64"}
+DEST=$DEST_DIR/fedora-coreos/$ARCH
+BASE_URL=https://builds.coreos.fedoraproject.org/prod/streams/$STREAM/builds/$VERSION/$ARCH
 
 # check stream/version exist based on the header response
-if ! curl -s -I $BASE_URL/fedora-coreos-$VERSION-metal.x86_64.raw.xz | grep -q -E '^HTTP/[0-9.]+ [23][0-9][0-9]' ; then
-  echo "Stream or Version not found"
+if ! curl -s -I $BASE_URL/fedora-coreos-$VERSION-metal.$ARCH.raw.xz | grep -q -E '^HTTP/[0-9.]+ [23][0-9][0-9]'; then
+  echo "Stream, Version or Architecture not found"
   exit 1
 fi
 
@@ -21,23 +22,22 @@ if [ ! -d "$DEST" ]; then
   mkdir -p $DEST
 fi
 
-echo "Downloading Fedora CoreOS $STREAM $VERSION images to $DEST"
+echo "Downloading Fedora CoreOS $STREAM $VERSION $ARCH images to $DEST"
 
 # PXE kernel
-echo "fedora-coreos-$VERSION-live-kernel-x86_64"
-curl -# $BASE_URL/fedora-coreos-$VERSION-live-kernel-x86_64 -o $DEST/fedora-coreos-$VERSION-live-kernel-x86_64
+echo "fedora-coreos-$VERSION-live-kernel-$ARCH"
+curl -# $BASE_URL/fedora-coreos-$VERSION-live-kernel-$ARCH -o $DEST/fedora-coreos-$VERSION-live-kernel-$ARCH
 
 # PXE initrd
-echo "fedora-coreos-$VERSION-live-initramfs.x86_64.img"
-curl -# $BASE_URL/fedora-coreos-$VERSION-live-initramfs.x86_64.img -o $DEST/fedora-coreos-$VERSION-live-initramfs.x86_64.img
+echo "fedora-coreos-$VERSION-live-initramfs.$ARCH.img"
+curl -# $BASE_URL/fedora-coreos-$VERSION-live-initramfs.$ARCH.img -o $DEST/fedora-coreos-$VERSION-live-initramfs.$ARCH.img
 
 # rootfs
-echo "fedora-coreos-$VERSION-live-rootfs.x86_64.img"
-curl -# $BASE_URL/fedora-coreos-$VERSION-live-rootfs.x86_64.img -o $DEST/fedora-coreos-$VERSION-live-rootfs.x86_64.img
+echo "fedora-coreos-$VERSION-live-rootfs.$ARCH.img"
+curl -# $BASE_URL/fedora-coreos-$VERSION-live-rootfs.$ARCH.img -o $DEST/fedora-coreos-$VERSION-live-rootfs.$ARCH.img
 
 # Install image
-echo "fedora-coreos-$VERSION-metal.x86_64.raw.xz"
-curl -# $BASE_URL/fedora-coreos-$VERSION-metal.x86_64.raw.xz -o $DEST/fedora-coreos-$VERSION-metal.x86_64.raw.xz
-echo "fedora-coreos-$VERSION-metal.x86_64.raw.xz.sig"
-curl -# $BASE_URL/fedora-coreos-$VERSION-metal.x86_64.raw.xz.sig -o $DEST/fedora-coreos-$VERSION-metal.x86_64.raw.xz.sig
-
+echo "fedora-coreos-$VERSION-metal.$ARCH.raw.xz"
+curl -# $BASE_URL/fedora-coreos-$VERSION-metal.$ARCH.raw.xz -o $DEST/fedora-coreos-$VERSION-metal.$ARCH.raw.xz
+echo "fedora-coreos-$VERSION-metal.$ARCH.raw.xz.sig"
+curl -# $BASE_URL/fedora-coreos-$VERSION-metal.$ARCH.raw.xz.sig -o $DEST/fedora-coreos-$VERSION-metal.$ARCH.raw.xz.sig
